### ISSUE TITLE
PR this plugin into various complements?

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/codeblock-completer#1]
I assume this would be a nice addition for various complements, since you would avoid splitting up suggesting functionality into dozens of small plugins? https://github.com/tadashi-aikawa/obsidian-various-complements-plugin

**Comment by kometenstaub** [comment]
I don't need the Various Complements plugin and would prefer it staying a plugin with a single use case.

**Comment by SkepticMystic** [comment]
I agree with Koala here. Various Complements does alot, and this is quite specific

**Comment by chrisgrieser** [comment]
yeah, was just a thought, I am fine either way 😊
