### ISSUE TITLE
context awareness

### ISSUE THREAD

**Issue by kometenstaub** [SkepticMystic/codeblock-completer#3]
When starting a code block with `auto pair markdown syntax` disabled, I first type
````
```
````

The suggestions show up as expected. To close the code block, I have to type it again. This time, it also shows the suggestions and I have to exit them with <kbd>Esc</kbd>. It would be great if it checked whether there was something with this form

````
```<some-lang>
````

before it and wouldn't show the suggester. That shouldn't make the Regex more difficult, but would warrant another regex check once the three backticks have triggered it.

https://github.com/SkepticMystic/codeblock-completer/blob/647b94994f8e519d311cfee05a72fb18ebed9c35/src/Suggester.ts#L26-L40

**Comment by SkepticMystic** [comment]
@kometenstaub How about I check if you have `auto pair markdown syntax` disabled, and add the bottom backticks, if so?
Or does that defeat the purpose of the setting?

**Comment by kometenstaub** [comment]
That could work. I have it disabled because it doesn't work well with vim mode, but in this context it might be useful.
Ideally there'd be an option to enable either of it, but I could also try to PR it if I don't end up liking your suggestion.

**Comment by SkepticMystic** [comment]
Alright, I'm gonna implement the suggestion. Let me know how it works for you.
I feel the use case of the plugin is so specific that one would probably always want the closing backticks

**Comment by SkepticMystic** [comment]
@kometenstaub give the latest version a try and let me know :)

**Comment by kometenstaub** [comment]
It works well, thank you :)
