### ISSUE TITLE
FR: Option to append `{}` for Code Block labels

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/codeblock-completer#5]
Another nice plugin I am using is code block label plugin (also beta), which uses `{}` after the language to set a file name.

Any chance you might add an option to append those? Would remove a tiny bit of friction :)

**Comment by SkepticMystic** [comment]
Added in latest release :)

**Comment by chrisgrieser** [comment]
my latest conversion with koala (paraphrased):

> koala: could you test this thing for breadcrumbs?
> me: yes. 
> me: doesn't work.
> koala: have you updated breadcrumbs?
> me: but I just updated yesterday.
> me: well, there is yet another breadcrumbs version. SkepticMystic just updates too quickly 🙈
