### ISSUE TITLE
Add option to remove plugin(s)

### ISSUE THREAD

**Issue by kzhovn** [SkepticMystic/codeblock-completer#7]
Thank you for the plugin! Means I actually remember what codeblocks I can use sometimes!

Admonitions are most of my suggestions, but I never use codeblock admonitions. It'd be convenient to be able to hide those suggestions.

**Comment by SkepticMystic** [comment]
Thanks for the suggestion! I've added this in the latest version, please let me know how it works for you :)

**Comment by kzhovn** [comment]
Thank you for such a quick response! It works great so far, though the UI in settings looks a little cluttered (might just be my theme?) But that's the tiniest of tiny nitpicks.
![Screenshot from 2022-05-13 12-40-29](https://user-images.githubusercontent.com/60860948/168329283-dd2d6caf-9cba-4ecb-80b2-ec679b65afd2.png)

**Comment by SkepticMystic** [comment]
Haha yeah, that's the best I got right now. I'm no stylist, so I'm open to changing how it looks. 
But I'm gonna close this issue for now as the original FR is finished :)
